### ISSUE TITLE
Error when Installing on Mac

### ISSUE THREAD

**Issue by adamhalasz** [mozilla/chromeless#150]
I would like to install Chromeless on Mac OS X Lion. I downloaded it, and when I run ./chromeless I get this error:

```
    Missing prerequisites!  I must download xulrunner to run.  Doing so
    Fetching xulrunner, 281 bytes from releases.mozilla.org
    | 0%                                                               100% |
    |***********************************************************************|
    Traceback (most recent call last):
      File "./chromeless", line 89, in <module>
        f.run()
      File "/Users/adam/Downloads/mozilla-chromeless-cabc4cb/impl/mozfetcher/_fetcher.py", line 142, in run
        self._fetch(descriptor)
      File "/Users/adam/Downloads/mozilla-chromeless-cabc4cb/impl/mozfetcher/_fetcher.py", line 111, in _fetch
        raise RuntimeError("download failure!  md5 mismatch!")
    RuntimeError: download failure!  md5 mismatch!
```

What is the problem, and how should I fix it? And I already have xulrunner 6.0.

**Comment by azendal** [comment]
same issue for me, leopard i have xulrunner 6.02

**Comment by lloyd** [comment]
should be fixed with 4e6c980479b0f91b76830dc7b58ff6ae9a0b3978

**Comment by azendal** [comment]
thx lloyd ill download and retry.

**Comment by azendal** [comment]
hey works really good. thx
