### ISSUE TITLE
installation problem with fetching xulrunner

### ISSUE THREAD

**Issue by nhoss2** [mozilla/chromeless#159]
I am on ubuntu 11.10 64 bit. I just git cloned your repository and when I run `./chromeless`, this is what I get:

```
Missing prerequisites!  I must download xulrunner to run.  Doing so
Fetching xulrunner, 376 bytes from releases.mozilla.org
| 0%                                                               100% |
|***********************************************************************|
Traceback (most recent call last):
  File "./chromeless", line 89, in <module>
    f.run()
  File "/home/nafis/apps/chromeless/impl/mozfetcher/_fetcher.py", line 142, in run
    self._fetch(descriptor)
  File "/home/nafis/apps/chromeless/impl/mozfetcher/_fetcher.py", line 111, in _fetch
    raise RuntimeError("download failure!  md5 mismatch!")
RuntimeError: download failure!  md5 mismatch!
```

**Comment by philippbosch** [comment]
Had the same problem. Was able to fix it with this change: philippbosch/chromeless@9da0aea92341d7d9e584c255cda36266c231dfef

**Comment by unclecheese** [comment]
Thanks a million.
