### ISSUE TITLE
Can't run any program.

### ISSUE THREAD

**Issue by CoderPuppy** [mozilla/chromeless#94]
I got this error

```
Path: C:\Chromeless\build\xulrunner/xulrunner.exe
Using Browser HTML at 'C:\Chromeless\programs\first_browser\index.html'
browser:
C:\Chromeless\programs\first_browser\index.html
Traceback (most recent call last):
  File "C:\Chromeless\chromeless", line 97, in <module>
    "--pkgdir", "packages/chromeless"
  File "C:\Chromeless\impl\cuddlefish\__init__.py", line 523, in run
    include_dep_tests=options.dep_tests
  File "C:\Chromeless\impl\cuddlefish\packaging.py", line 290, in generate_build
_for_target
    update_manifest_with_fileinfo(deps, DEFAULT_LOADER, manifest)
  File "C:\Chromeless\impl\cuddlefish\manifest.py", line 210, in update_manifest
_with_fileinfo
    target.pop()
IndexError: pop from empty list
```

It might be something to do with my fixing it to work on my system.

**Comment by CoderPuppy** [comment]
Fixed it was something with the `require` finder that it found commented requires.
I took them out.
